//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tic_Tac_Toe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tic_Tac_Toe.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string MainSubtitle {
            get {
                return ResourceManager.GetString("MainSubtitle", resourceCulture);
            }
        }
        
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        public static string BackToMenu {
            get {
                return ResourceManager.GetString("BackToMenu", resourceCulture);
            }
        }
        
        public static string ConfirmBackToMenu {
            get {
                return ResourceManager.GetString("ConfirmBackToMenu", resourceCulture);
            }
        }
        
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        public static string PlayerSelection {
            get {
                return ResourceManager.GetString("PlayerSelection", resourceCulture);
            }
        }
        
        public static string ChooseGameSettings {
            get {
                return ResourceManager.GetString("ChooseGameSettings", resourceCulture);
            }
        }
        
        public static string GameMode {
            get {
                return ResourceManager.GetString("GameMode", resourceCulture);
            }
        }
        
        public static string PlayerVsPlayer {
            get {
                return ResourceManager.GetString("PlayerVsPlayer", resourceCulture);
            }
        }
        
        public static string PlayWithBot {
            get {
                return ResourceManager.GetString("PlayWithBot", resourceCulture);
            }
        }
        
        public static string PlayerX {
            get {
                return ResourceManager.GetString("PlayerX", resourceCulture);
            }
        }
        
        public static string Crosses {
            get {
                return ResourceManager.GetString("Crosses", resourceCulture);
            }
        }
        
        public static string PlayerO {
            get {
                return ResourceManager.GetString("PlayerO", resourceCulture);
            }
        }
        
        public static string Noughts {
            get {
                return ResourceManager.GetString("Noughts", resourceCulture);
            }
        }
        
        public static string BotDifficulty {
            get {
                return ResourceManager.GetString("BotDifficulty", resourceCulture);
            }
        }
        
        public static string DifficultyEasy {
            get {
                return ResourceManager.GetString("DifficultyEasy", resourceCulture);
            }
        }
        
        public static string DifficultyMedium {
            get {
                return ResourceManager.GetString("DifficultyMedium", resourceCulture);
            }
        }
        
        public static string DifficultyHard {
            get {
                return ResourceManager.GetString("DifficultyHard", resourceCulture);
            }
        }
        
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        public static string StatisticsTitle {
            get {
                return ResourceManager.GetString("StatisticsTitle", resourceCulture);
            }
        }
        
        public static string TrackPerformance {
            get {
                return ResourceManager.GetString("TrackPerformance", resourceCulture);
            }
        }
        
        public static string SelectPlayer {
            get {
                return ResourceManager.GetString("SelectPlayer", resourceCulture);
            }
        }
        
        public static string SelectPlayerToView {
            get {
                return ResourceManager.GetString("SelectPlayerToView", resourceCulture);
            }
        }
        
        public static string GameHistory {
            get {
                return ResourceManager.GetString("GameHistory", resourceCulture);
            }
        }
        
        public static string PlayerStats {
            get {
                return ResourceManager.GetString("PlayerStats", resourceCulture);
            }
        }
        
        public static string TotalGames {
            get {
                return ResourceManager.GetString("TotalGames", resourceCulture);
            }
        }
        
        public static string Wins {
            get {
                return ResourceManager.GetString("Wins", resourceCulture);
            }
        }
        
        public static string Draws {
            get {
                return ResourceManager.GetString("Draws", resourceCulture);
            }
        }
        
        public static string Losses {
            get {
                return ResourceManager.GetString("Losses", resourceCulture);
            }
        }
        
        public static string WinRate {
            get {
                return ResourceManager.GetString("WinRate", resourceCulture);
            }
        }
        
        public static string HistoryHeader {
            get {
                return ResourceManager.GetString("HistoryHeader", resourceCulture);
            }
        }
        
        public static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        public static string Loss {
            get {
                return ResourceManager.GetString("Loss", resourceCulture);
            }
        }
        
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        public static string NoGamesYet {
            get {
                return ResourceManager.GetString("NoGamesYet", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string SettingsSubtitle {
            get {
                return ResourceManager.GetString("SettingsSubtitle", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        public static string LanguageUkrainian {
            get {
                return ResourceManager.GetString("LanguageUkrainian", resourceCulture);
            }
        }
        
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        public static string ErrorLoadingPlayers {
            get {
                return ResourceManager.GetString("ErrorLoadingPlayers", resourceCulture);
            }
        }
        
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        public static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        public static string StartupError {
            get {
                return ResourceManager.GetString("StartupError", resourceCulture);
            }
        }
    }
}
